# Generated by Django 3.0.5 on 2024-09-25 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0021_auto_20240925_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='scans',
            field=models.FileField(blank=True, null=True, upload_to='scans'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='report',
            field=models.FileField(blank=True, null=True, upload_to='reports'),
        ),
    ]
