# Generated by Django 3.0.5 on 2024-09-26 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0023_remove_patient_assigneddoctorid_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='report',
        ),
        migrations.CreateModel(
            name='Reports',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.FileField(blank=True, null=True, upload_to='reports')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='report', to='hospital.Patient')),
            ],
        ),
    ]
