# Generated by Django 5.0.1 on 2024-09-26 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0025_patient_accession_patient_center_patient_department_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='doctor_refer_by',
        ),
    ]
