# Generated by Django 5.0.1 on 2024-09-26 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0026_remove_patient_doctor_refer_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='images',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
