# Generated by Django 5.0.1 on 2024-09-26 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0024_auto_20240926_0623'),
        ('hospital', '0027_alter_patient_images'),
    ]

    operations = [
    ]
